name: Test

on:
  push:
   branches:
     - "v1.2"
  workflow_dispatch:

jobs:
  test-on-public-repo:
    runs-on: ubuntu-latest
    steps:
    - id: get-version-action
      name: Get latest release's version of `actions/runner` using action
      uses: fangqiuming/latest-release-version@main
      with:
        repository: actions/runner
    - id: get-version-curl
      name: Get latest release's version of `actions/runner` using cURL
      shell: bash
      run: |
        URL=$(curl -Ls -o /dev/null -w %{url_effective} \
        https://github.com/actions/runner/releases/latest)
        TAG_NAME=${URL##*/}
        echo "TAG_NAME: $TAG_NAME"
        echo "::set-output name=tag_name::$(echo $TAG_NAME)"
    - name: A/B Check
      if: steps.get-version-action.outputs.tag_name != steps.get-version-curl.outputs.tag_name
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed("${{ steps.get-version-action.outputs.tag_name }} \
          and ${{ steps.get-version-curl.outputs.tag_name }} are not equivalent!')
  test-on-private-repo-include-pre-release:
    runs-on: ubuntu-latest
    steps:
    - id: get-version-action
      name: Get latest release or prerelease's version(published_at) \
        of `fangqiuming/open`
      uses: fangqiuming/latest-release-version@main
      with:
        repository: fangqiuming/open
        token: ${{ secrets.REPO }}
        property: published_at
        include_pre: 'true'
    - name: A/B Check
      if: steps.get-version-action.outputs.version != '2022-03-29T09:10:06Z'
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed("${{ steps.get-version-action.outputs.version }} \
          and 2022-03-29T09:10:06Z are not equivalent!')
  test-on-repo-with-no-release:
    runs-on: ubuntu-latest
    steps:
    - id: get-version-action
      name: Get latest release of `fangqiuming/stellaris_cn`
      uses: fangqiuming/latest-release-version@main
      with:
        repository:  fangqiuming/stellaris_cn 
    - name: A/B Check
      if: steps.get-version-action.outputs.version != 'v0.0.0'
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed("${{ steps.get-version-action.outputs.version }} \
          and v0.0.0 are not equivalent!')